language: java
jdk:
   - oraclejdk8
before_install:
   - wget http://services.gradle.org/distributions/gradle-2.3-bin.zip
   - unzip gradle-2.3-bin.zip
   - export GRADLE_HOME=$PWD/gradle-2.3
   - export PATH=$GRADLE_HOME/bin:$PATH